## 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

In [14]:
x=np.zeros(10)
x[4]=1
print("Null Vector of size 10 but the 5th value is 1 :\n", x)

Null Vector of size 10 but the 5th value is 1 :
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [12]:
v = np.arange(10,49)
print("Vector with values ranging from 10 to 49 :\n", v)

Vector with values ranging from 10 to 49 :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [40]:
a = np.array([1,2,0,0,4,0])
np.where(a > 0)

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [41]:
b = np.random.random((10,10))
print("Original Array : \n", b)
bmin, bmax = b.min(), b.max()
print("Minimum and Maximum Values : \n", bmin, bmax)

Original Array : 
 [[0.63937349 0.13568637 0.44200625 0.08034965 0.87234392 0.59422499
  0.28850279 0.17931152 0.72126932 0.38472285]
 [0.7180244  0.55583792 0.77306767 0.945503   0.12850908 0.5180691
  0.89135193 0.55099907 0.82140863 0.84735815]
 [0.86661548 0.8984308  0.44976206 0.82721924 0.52759718 0.51567002
  0.5219049  0.18541147 0.97504336 0.22285176]
 [0.31241576 0.43704345 0.45689188 0.60985294 0.34386944 0.2092969
  0.66724589 0.60731481 0.70133479 0.10266124]
 [0.38368887 0.8581452  0.67771494 0.13828211 0.00218956 0.79921105
  0.50656828 0.50394919 0.56942387 0.14522098]
 [0.96369472 0.95839065 0.47898583 0.09248874 0.55408201 0.87542485
  0.95213991 0.26823591 0.52468086 0.53385919]
 [0.63573258 0.99163544 0.78377258 0.61742232 0.51300746 0.60597753
  0.47103827 0.69218488 0.92243315 0.66742779]
 [0.05668405 0.49982229 0.50509131 0.73293436 0.3376293  0.69038803
  0.51196298 0.22753498 0.54376496 0.68182897]
 [0.0842474  0.66841757 0.50027214 0.63245921 0.13255146 0.0246

## 6. Create a random vector of size 30 and find the mean value.

In [49]:
c = np.random.random(30)
print("Original array : \n", c)
print("Mean Value : \n", np.mean(c))

Original array : 
 [0.55234012 0.1235457  0.39339784 0.03373868 0.34070223 0.4196073
 0.27807349 0.49701214 0.8746888  0.43082348 0.94575887 0.09319825
 0.17595757 0.68859735 0.10491248 0.65371142 0.92022181 0.53598293
 0.16140441 0.84503061 0.22110878 0.25789448 0.6258709  0.5392296
 0.71066959 0.99112872 0.27443242 0.14998225 0.46289772 0.7614557 ]
Mean Value : 
 0.46877918886117487
